### ISSUE TITLE
support font awesome icon instead of SVG

### ISSUE THREAD

**Issue by zeing** [tailwindcss/custom-forms#55]
Can use font awesome icon like 
```
customForms: theme => ({
      default: {
        select: {
          icon: '<i className="fas fa-sort-down"></i>',
        },
      },
    })
```
instead of SVG Icon

**Comment by mornir** [comment]
It's better to use SVG for icons: https://www.lambdatest.com/blog/its-2019-lets-end-the-debate-on-icon-fonts-vs-svg-icons/
As for convenience, Font-Awesome lets you easily copy paste the SVG from their website.

**Comment by mpalpha** [comment]
There are cases at my company where you would need to use either or both.

Currently, doesn't it support both options instead of forcing one or another? 
For example, can't you just use the <i...> font-awesome icon element or inline <svg...> element here? 
Why would this need to change? 
Shouldn't you just use/create a plugin if you need more functionality.

**Comment by zeing** [comment]
thank you all
